# @package _global_

# specify here default training configuration
defaults:
  - path: default.yaml
  - trainer: default.yaml
  - callbacks: default.yaml # set this to null if you don't want to use callbacks
  - logger: tensorboard.yaml # set logger here or use command line (e.g. `python run.py logger=wandb`)
  - model: null
  - datamodule: null

  - experiment: null
  - hparams_search: null

  # hydra
  - hydra: default.yaml
  # > enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

# use `python run.py debug=true` for easy debugging!
# this will run 1 train, val and test loop with only 1 batch
# equivalent to running `python run.py trainer.fast_dev_run=true`
# (this is placed here just for easier access from command line)
debug: False

# pretty print config at the start of the run using Rich library
print_config: True

# disable python warnings if they annoy you
ignore_warnings: True
